apiVersion: v1
kind: Namespace
metadata:
  name: lateread-dev

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: lateread-dev
spec:
  selector:
    matchLabels:
      app: nodejs
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodongo
        image: gcr.io/homeprojects-271419/hw:v1
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: lateread-dev
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
